name: Pytest Check
on: [pull_request]

jobs:
  test:
    runs-on:
      group: big-data
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Run Tests
        run: uv run --extra test pytest tests
