name: Pytest Check
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Remove junk
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: "true"
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Run Tests
        run: uv run --extra test pytest tests
